### ISSUE TITLE
(unimportant): Add standardized nav bar to the dataset pages

### ISSUE THREAD

**Issue by flaneuse** [biothings/discovery-app#177]
**Describe the solution you'd like**
Is there a reason why the [Dataset pages](https://discovery.biothings.io/dataset/9f2318febbbfa710) don't have the same nav bar as the rest of the site?  Maybe it's just me, but I find it annoying when I want to navigate from that page to another location.  Thanks, M!

**Comment by marcodarko** [comment]
If I recall correctly I think it was because they wanted to remove all additional navigation in case someone shared that page, it would be just a simple as it could be. We can revisit that idea tho. Another reason was to make that page as light as possible so google indexer would load the page asap.

**Comment by marcodarko** [comment]
This will be taken care of in the ssr app which we will switch to soon hopefully. For now due to limitations we have to keep it.
