### ISSUE TITLE
Extensions including namespaces in DDE cannot be visualized in DDE

### ISSUE THREAD

**Issue by ljgarcia** [biothings/discovery-app#247]
**Describe the bug**
Extensions including namespaces in DDE cannot be visualized in DDE, the interface gives an error "path to schema:Thing not found"

**To Reproduce**
Extend from a DDE space, for instance [maSMP](https://discovery.biothings.io/ns/maSMP) and add some validation rules.
Download the created file and add it to a GitHub repo, for instance https://raw.githubusercontent.com/ljgarcia/Deleteme/master/schemas/OutputMngPlanProfile.jsonld
Try to visualize it with DDE playground

**Expected behavior**
I would expect the file to be correctly loaded and visualized in DDE, instead I get an error

**Screenshots**
![image](https://github.com/biothings/discovery-app/assets/5427252/07169be0-e8df-435f-a355-66f173655006)

**Additional context**

**Comment by marcodarko** [comment]
@ljgarcia we noticed a small typo that could be cause in this schema: https://raw.githubusercontent.com/zbmed-semtec/maSMPs/main/schema/maSMP_schema_v2/maSMP_v2.jsonld
<img width="519" alt="Screenshot 2024-01-18 at 10 17 34 AM" src="https://github.com/biothings/discovery-app/assets/23092057/3f975648-6c8b-4196-bfad-4ea223a4bdf3">
There's an extra colon **"maSMP:"** in the key name that effectively changes the name of the namespace so that could be the cause why the backend can't find a relation to the origin. 
If you can change that we can rule out this possibility but there's a good chance that's it because we took a look at the subclass and everything looked good there. 
Let me know if you have any questions!

**Comment by ljgarcia** [comment]
Oh! I would have not realize about it without your help, thanks a lot, it works now like charming!
I will close this issue as "No Issue" with the option "Close as not planned" as there is nothing to fix on your side, hope this is fine.
Thanks a lot!
