### ISSUE TITLE
Capture and display the name and the url for ontology-based fields in NIAID Dataset, outbreak

### ISSUE THREAD

**Issue by flaneuse** [biothings/discovery-app#62]
Right now, only the url is saved for ontology-based fields like `species`, `measurementTechnique`, `infectiousAgent`, `infectiousDisease`.  To improve user experience, also save and display the name, e.g. "Homo sapiens" 
and url: http://purl.obolibrary.org/obo/NCBITaxon_9606

Requested in DDWG meeting.

**Comment by flaneuse** [comment]
e.g. "Zika" is more useful than http://purl...
<img width="643" alt="Screen Shot 2020-12-15 at 1 20 05 PM" src="https://user-images.githubusercontent.com/8041065/102262164-4bc51f80-3ed8-11eb-99e7-4eb0a0b8f0ff.png">

**Comment by marcodarko** [comment]
This depends on your json schema requirements, if you specify that you need both url and name or anything else, we'll populate it for you.  On the UI side is a field name is available it will be display instead otherwise the string or object.  However if a url is detected a tip will try to match it a human readable name and display that on hover.  Note: anything in green is a direct representation of the schema values, we can't add another field or change the data type as this will result in errors.
